package th.ac.ku.kps.eng.cpe.soaProject.model;
// Generated Mar 27, 2023, 9:07:29 PM by Hibernate Tools 6.0.2.Final

import java.util.HashSet;
import java.util.Set;

/**
 * CourseMenu generated by hbm2java
 */
public class CourseMenu implements java.io.Serializable {

	private Integer courseMenuId;
	private String courseMenuName;
	private Set menuInCourses = new HashSet(0);
	private Set reservations = new HashSet(0);

	public CourseMenu() {
	}

	public CourseMenu(String courseMenuName) {
		this.courseMenuName = courseMenuName;
	}

	public CourseMenu(String courseMenuName, Set menuInCourses, Set reservations) {
		this.courseMenuName = courseMenuName;
		this.menuInCourses = menuInCourses;
		this.reservations = reservations;
	}

	public Integer getCourseMenuId() {
		return this.courseMenuId;
	}

	public void setCourseMenuId(Integer courseMenuId) {
		this.courseMenuId = courseMenuId;
	}

	public String getCourseMenuName() {
		return this.courseMenuName;
	}

	public void setCourseMenuName(String courseMenuName) {
		this.courseMenuName = courseMenuName;
	}

	public Set getMenuInCourses() {
		return this.menuInCourses;
	}

	public void setMenuInCourses(Set menuInCourses) {
		this.menuInCourses = menuInCourses;
	}

	public Set getReservations() {
		return this.reservations;
	}

	public void setReservations(Set reservations) {
		this.reservations = reservations;
	}

}
