package th.ac.ku.kps.eng.cpe.soaProject.model;
// Generated Mar 27, 2023, 9:07:29 PM by Hibernate Tools 6.0.2.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Menu generated by hbm2java
 */
public class Menu implements java.io.Serializable {

	private Integer menuId;
	private MenuType menuType;
	private String menuName;
	private String menuDescription;
	private Set menuInCourses = new HashSet(0);

	public Menu() {
	}

	public Menu(String menuName, String menuDescription) {
		this.menuName = menuName;
		this.menuDescription = menuDescription;
	}

	public Menu(MenuType menuType, String menuName, String menuDescription, Set menuInCourses) {
		this.menuType = menuType;
		this.menuName = menuName;
		this.menuDescription = menuDescription;
		this.menuInCourses = menuInCourses;
	}

	public Integer getMenuId() {
		return this.menuId;
	}

	public void setMenuId(Integer menuId) {
		this.menuId = menuId;
	}

	public MenuType getMenuType() {
		return this.menuType;
	}

	public void setMenuType(MenuType menuType) {
		this.menuType = menuType;
	}

	public String getMenuName() {
		return this.menuName;
	}

	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}

	public String getMenuDescription() {
		return this.menuDescription;
	}

	public void setMenuDescription(String menuDescription) {
		this.menuDescription = menuDescription;
	}

	public Set getMenuInCourses() {
		return this.menuInCourses;
	}

	public void setMenuInCourses(Set menuInCourses) {
		this.menuInCourses = menuInCourses;
	}

}
