package th.ac.ku.kps.eng.cpe.soaProject.model;
// Generated Mar 27, 2023, 9:07:29 PM by Hibernate Tools 6.0.2.Final

/**
 * MenuInCourse generated by hbm2java
 */
public class MenuInCourse implements java.io.Serializable {

	private Integer menuInCourseId;
	private CourseMenu courseMenu;
	private Menu menu;

	public MenuInCourse() {
	}

	public MenuInCourse(CourseMenu courseMenu, Menu menu) {
		this.courseMenu = courseMenu;
		this.menu = menu;
	}

	public Integer getMenuInCourseId() {
		return this.menuInCourseId;
	}

	public void setMenuInCourseId(Integer menuInCourseId) {
		this.menuInCourseId = menuInCourseId;
	}

	public CourseMenu getCourseMenu() {
		return this.courseMenu;
	}

	public void setCourseMenu(CourseMenu courseMenu) {
		this.courseMenu = courseMenu;
	}

	public Menu getMenu() {
		return this.menu;
	}

	public void setMenu(Menu menu) {
		this.menu = menu;
	}

}
