package th.ac.ku.kps.eng.cpe.soaProject.model;
// Generated Apr 6, 2023, 9:43:25 AM by Hibernate Tools 6.0.2.Final

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * MenuInCourse generated by hbm2java
 */
public class MenuInCourse implements java.io.Serializable {

	private Integer menuInCourseId;
	@JsonIgnore
	private CourseMenu courseMenu;
	@JsonIgnore
	private Menu menu;

	public MenuInCourse() {
	}

	public MenuInCourse(CourseMenu courseMenu, Menu menu) {
		this.courseMenu = courseMenu;
		this.menu = menu;
	}

	public Integer getMenuInCourseId() {
		return this.menuInCourseId;
	}

	public void setMenuInCourseId(Integer menuInCourseId) {
		this.menuInCourseId = menuInCourseId;
	}

	public CourseMenu getCourseMenu() {
		return this.courseMenu;
	}

	public void setCourseMenu(CourseMenu courseMenu) {
		this.courseMenu = courseMenu;
	}

	public Menu getMenu() {
		return this.menu;
	}

	public void setMenu(Menu menu) {
		this.menu = menu;
	}

}
