package th.ac.ku.kps.eng.cpe.soaProject.model;
// Generated Apr 6, 2023, 9:43:25 AM by Hibernate Tools 6.0.2.Final

import java.sql.Date;
import java.sql.Time;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Reservation generated by hbm2java
 */
public class Reservation implements java.io.Serializable {

	private Integer reservationId;
	@JsonIgnore
	private TableRestaurant tableRestaurant;
	@JsonIgnore
	private CourseMenu courseMenu;
	@JsonIgnore
	private User user;
	private Date reservationDate;
	private Time reservationTimeStart;
	private Time reservationTimeEnd;
	private String reservationStatus;

	public Reservation() {
	}

	public Reservation(TableRestaurant tableRestaurant, CourseMenu courseMenu, User user) {
		this.tableRestaurant = tableRestaurant;
		this.courseMenu = courseMenu;
		this.user = user;
	}

	public Reservation(TableRestaurant tableRestaurant, CourseMenu courseMenu, User user, Date reservationDate,
			Time reservationTimeStart, Time reservationTimeEnd, String reservationStatus) {
		this.tableRestaurant = tableRestaurant;
		this.courseMenu = courseMenu;
		this.user = user;
		this.reservationDate = reservationDate;
		this.reservationTimeStart = reservationTimeStart;
		this.reservationTimeEnd = reservationTimeEnd;
		this.reservationStatus = reservationStatus;
	}

	public Integer getReservationId() {
		return this.reservationId;
	}

	public void setReservationId(Integer reservationId) {
		this.reservationId = reservationId;
	}

	public TableRestaurant getTableRestaurant() {
		return this.tableRestaurant;
	}

	public void setTableRestaurant(TableRestaurant tableRestaurant) {
		this.tableRestaurant = tableRestaurant;
	}

	public CourseMenu getCourseMenu() {
		return this.courseMenu;
	}

	public void setCourseMenu(CourseMenu courseMenu) {
		this.courseMenu = courseMenu;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getReservationDate() {
		return this.reservationDate;
	}

	public void setReservationDate(Date reservationDate) {
		this.reservationDate = reservationDate;
	}

	public Time getReservationTimeStart() {
		return this.reservationTimeStart;
	}

	public void setReservationTimeStart(Time reservationTimeStart) {
		this.reservationTimeStart = reservationTimeStart;
	}

	public Time getReservationTimeEnd() {
		return this.reservationTimeEnd;
	}

	public void setReservationTimeEnd(Time reservationTimeEnd) {
		this.reservationTimeEnd = reservationTimeEnd;
	}

	public String getReservationStatus() {
		return this.reservationStatus;
	}

	public void setReservationStatus(String reservationStatus) {
		this.reservationStatus = reservationStatus;
	}

}
