package th.ac.ku.kps.eng.cpe.soaProject.model;

import com.fasterxml.jackson.annotation.JsonIgnore;

// Generated Mar 5, 2023, 2:05:21 PM by Hibernate Tools 6.0.2.Final

/**
 * Reservation generated by hbm2java
 */
public class Reservation implements java.io.Serializable {

	private Integer reservationId;
	@JsonIgnore
	private User user;
	@JsonIgnore
	private CourseMenu courseMenu;
	@JsonIgnore
	private TableRestaurant tableRestaurant;

	public Reservation() {
	}

	public Reservation(User user, CourseMenu courseMenu, TableRestaurant tableRestaurant) {
		this.user = user;
		this.courseMenu = courseMenu;
		this.tableRestaurant = tableRestaurant;
	}

	public Integer getReservationId() {
		return this.reservationId;
	}

	public void setReservationId(Integer reservationId) {
		this.reservationId = reservationId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public CourseMenu getCourseMenu() {
		return this.courseMenu;
	}

	public void setCourseMenu(CourseMenu courseMenu) {
		this.courseMenu = courseMenu;
	}

	public TableRestaurant getTableRestaurant() {
		return this.tableRestaurant;
	}

	public void setTableRestaurant(TableRestaurant tableRestaurant) {
		this.tableRestaurant = tableRestaurant;
	}

}
