package th.ac.ku.kps.eng.cpe.soaProject.model;
// Generated Mar 5, 2023, 2:05:21 PM by Hibernate Tools 6.0.2.Final

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * TableRestaurant generated by hbm2java
 */
public class TableRestaurant implements java.io.Serializable {

	private Integer tableRestaurantId;
	private String tableRestaurantCode;
	private int tableRestaurantNumberOfChair;
//	@JsonIgnore
	private Set reservations = new HashSet(0);

	public TableRestaurant() {
	}

	public TableRestaurant(String tableRestaurantCode, int tableRestaurantNumberOfChair) {
		this.tableRestaurantCode = tableRestaurantCode;
		this.tableRestaurantNumberOfChair = tableRestaurantNumberOfChair;
	}

	public TableRestaurant(String tableRestaurantCode, int tableRestaurantNumberOfChair, Set reservations) {
		this.tableRestaurantCode = tableRestaurantCode;
		this.tableRestaurantNumberOfChair = tableRestaurantNumberOfChair;
		this.reservations = reservations;
	}

	public Integer getTableRestaurantId() {
		return this.tableRestaurantId;
	}

	public void setTableRestaurantId(Integer tableRestaurantId) {
		this.tableRestaurantId = tableRestaurantId;
	}

	public String getTableRestaurantCode() {
		return this.tableRestaurantCode;
	}

	public void setTableRestaurantCode(String tableRestaurantCode) {
		this.tableRestaurantCode = tableRestaurantCode;
	}

	public int getTableRestaurantNumberOfChair() {
		return this.tableRestaurantNumberOfChair;
	}

	public void setTableRestaurantNumberOfChair(int tableRestaurantNumberOfChair) {
		this.tableRestaurantNumberOfChair = tableRestaurantNumberOfChair;
	}

	public Set getReservations() {
		return this.reservations;
	}

	public void setReservations(Set reservations) {
		this.reservations = reservations;
	}

}
