package th.ac.ku.kps.eng.cpe.soaProject.model;
// Generated Mar 5, 2023, 2:05:21 PM by Hibernate Tools 6.0.2.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * User generated by hbm2java
 */

public class User implements java.io.Serializable {

	private Integer userId;
	private String userUsername;
	private String userPassword;
	private String userFirstname;
	private String userLastname;
	private String userPhonenumber;
	private Set reservations = new HashSet(0);

	public User() {
	}

	public User(String userUsername, String userPassword, String userFirstname, String userLastname,
			String userPhonenumber) {
		this.userUsername = userUsername;
		this.userPassword = userPassword;
		this.userFirstname = userFirstname;
		this.userLastname = userLastname;
		this.userPhonenumber = userPhonenumber;
	}

	public User(String userUsername, String userPassword, String userFirstname, String userLastname,
			String userPhonenumber, Set reservations) {
		this.userUsername = userUsername;
		this.userPassword = userPassword;
		this.userFirstname = userFirstname;
		this.userLastname = userLastname;
		this.userPhonenumber = userPhonenumber;
		this.reservations = reservations;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserUsername() {
		return this.userUsername;
	}

	public void setUserUsername(String userUsername) {
		this.userUsername = userUsername;
	}

	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	public String getUserFirstname() {
		return this.userFirstname;
	}

	public void setUserFirstname(String userFirstname) {
		this.userFirstname = userFirstname;
	}

	public String getUserLastname() {
		return this.userLastname;
	}

	public void setUserLastname(String userLastname) {
		this.userLastname = userLastname;
	}

	public String getUserPhonenumber() {
		return this.userPhonenumber;
	}

	public void setUserPhonenumber(String userPhonenumber) {
		this.userPhonenumber = userPhonenumber;
	}

	public Set getReservations() {
		return this.reservations;
	}

	public void setReservations(Set reservations) {
		this.reservations = reservations;
	}

}
